SELECT 
IF (
    DATE_FORMAT(DATETIME, '%H') LIKE '0%', 
    SUBSTRING(DATE_FORMAT(DATETIME, '%H'), 2, 1), 
    DATE_FORMAT(DATETIME, '%H')
)  AS `HOUR`, 
COUNT(*) as `COUNT`
FROM ANIMAL_OUTS
GROUP BY `HOUR`
HAVING `HOUR` >= 9 AND `HOUR` < 20
ORDER BY DATE_FORMAT(DATETIME, '%H') ASC