SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AS AO
JOIN ANIMAL_INS AS AI ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE TIMESTAMPDIFF(MINUTE, AI.DATETIME, AO.DATETIME) >= 0
ORDER BY TIMESTAMPDIFF(MINUTE, AI.DATETIME, AO.DATETIME) DESC
LIMIT 2